name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    env:
      SELENIUM_URL: http://selenium__standalone-chrome:4444/wd/hub # BitBucket: http://0.0.0.0:4444/wd/hub
    services:
      selenium:
        image: selenium/standalone-chrome:latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.63.0
        with: 
          ruby-version: 2.7.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'
          
      - name: Install Yarn
        run: yarn install
        
      - name: Install Depencencies
        run: gem install bundler
        
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-        

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3            
        
      - name: Prepare Database
        run: bundle exec rails db:prepare

      - name: Run Tests
        run: RAILS_ENV=test bundle exec rails test:system
